### ISSUE TITLE
llvm not buildable on glibc system

### ISSUE THREAD

**Issue by joker25** [iglunix/iglunix#17]
Hello,
i have a problem autobuilding iglunix.
When i come to the stage-3 build of base/llvm it will stop with the error:

> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix/base/llvm/src/llvm-15.0.0/llvm/lib/MCA/Stages/InOrderIssueStage.cpp:14:
> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix/base/llvm/src/llvm-15.0.0/llvm/include/llvm/MCA/Stages/InOrderIssueStage.h:17:
> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix/base/llvm/src/llvm-15.0.0/llvm/include/llvm/MCA/CustomBehaviour.h:21:
> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix/base/llvm/src/llvm-15.0.0/llvm/include/llvm/MC/MCInst.h:19:
> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix/base/llvm/src/llvm-15.0.0/llvm/include/llvm/ADT/StringRef.h:21:
> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix-bootstrap/sysroot//include/c++/v1/string:524:
> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix-bootstrap/sysroot//include/c++/v1/cstdio:99:
> In file included from /home/user/IGLUNIX/iglunix-autobuild/build/iglunix-bootstrap/sysroot//include/c++/v1/stdio.h:107:
> /usr/include/stdio.h:52:9: error: unknown type name '__gnuc_va_list'
> typedef __gnuc_va_list va_list;
>         ^
> /usr/include/stdio.h:366:8: error: unknown type name '__gnuc_va_list'
>                      __gnuc_va_list __arg);
>                      ^
> /usr/include/stdio.h:371:54: error: unknown type name '__gnuc_va_list'
> extern int vprintf (const char *__restrict __format, __gnuc_va_list __arg);
>                                                      ^
> /usr/include/stdio.h:374:8: error: unknown type name '__gnuc_va_list'
>                      __gnuc_va_list __arg) __THROWNL;
>                      ^
> /usr/include/stdio.h:383:42: error: unknown type name '__gnuc_va_list'
>                       const char *__restrict __format, __gnuc_va_list __arg)
>                                                        ^
> /usr/include/stdio.h:391:9: error: unknown type name '__gnuc_va_list'
>                       __gnuc_va_list __arg)
>                       ^
> 
> 

> /usr/include/stdio.h:404:8: error: unknown type name '__gnuc_va_list'
>                      __gnuc_va_list __arg)
>                      ^
> 

The problem seems, that llvm is trying to include the include files of /usr/include too

**Comment by aheirman** [comment]
Hey, it should now work since we have CI, it only works on ubuntu 20.04.

If your issue persists feel free to reopen the issue.
